# Generated by Django 5.1.5 on 2025-02-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_rename_user_like_user0_alter_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comments',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='likes',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
