# Generated by Django 5.1.5 on 2025-02-10 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_remove_post_like_comment_like_alter_post_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='comments',
            new_name='comment',
        ),
    ]
