# Generated by Django 5.1.5 on 2025-02-10 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_rename_comments_post_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='like',
            new_name='likes',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='comment',
            new_name='comments',
        ),
    ]
