# Generated by Django 5.1.5 on 2025-02-12 11:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_alter_comment_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='user',
            new_name='users',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='author',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('users', 'post')},
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('author', 'text')},
        ),
    ]
