# Generated by Django 5.1.5 on 2025-02-12 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_rename_user_like_users_rename_user_post_author_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set(),
        ),
    ]
